version: '3.6'
volumes:
  jenkinshome:
    driver: local

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: unless-stopped
    volumes:
      - jenkinshome:/var/jenkins_home:Z
    ports:
      - 8080:8080
      - 50000:50000

